package com.github.rickmvi.jtoolbox.annotation.processor.codegen;

import java.io.PrintWriter;

public class CodeWriter implements AutoCloseable {
    private final PrintWriter writer;
    private int indentLevel = 0;
    private static final String INDENT = "    ";

    public CodeWriter(PrintWriter writer) {
        this.writer = writer;
    }

    public CodeWriter writePackage(String packageName) {
        writer.println("package " + packageName + ";");
        return this;
    }

    public CodeWriter writeImport(String importName) {
        writer.println("import " + importName + ";");
        return this;
    }

    public CodeWriter writeGeneratedComment() {
        writer.println("/**");
        writer.println(" * Generated by JToolBox Annotation Processor");
        writer.println(" * DO NOT EDIT MANUALLY");
        writer.println(" */");
        return this;
    }

    public CodeWriter writeLine() {
        writer.println();
        return this;
    }

    public CodeWriter writeLine(String line) {
        writer.println(line);
        return this;
    }

    public CodeWriter write(String text) {
        writer.print(text);
        return this;
    }

    public CodeWriter writeIndent() {
        for (int i = 0; i < indentLevel; i++) {
            writer.print(INDENT);
        }
        return this;
    }

    public CodeWriter beginClass(String modifiers, String className) {
        writer.println(modifiers + " class " + className + " {");
        indentLevel++;
        return this;
    }

    public CodeWriter beginClass(String modifiers, String className, String extendsClass) {
        writer.println(modifiers + " class " + className + " extends " + extendsClass + " {");
        indentLevel++;
        return this;
    }

    public CodeWriter endClass() {
        indentLevel--;
        writeIndent().writeLine("}");
        return this;
    }

    public CodeWriter beginMethod(String modifiers, String returnType, String methodName, String... params) {
        writeIndent().write(modifiers + " " + returnType + " " + methodName + "(");
        for (int i = 0; i < params.length; i += 2) {
            writer.print(params[i] + " " + params[i + 1]);
            if (i < params.length - 2) {
                writer.print(", ");
            }
        }
        writer.println(") {");
        indentLevel++;
        return this;
    }

    public CodeWriter endMethod() {
        indentLevel--;
        writeIndent().writeLine("}");
        return this;
    }

    public CodeWriter beginBlock() {
        writeIndent().writeLine("{");
        indentLevel++;
        return this;
    }

    public CodeWriter endBlock() {
        indentLevel--;
        writeIndent().writeLine("}");
        return this;
    }

    public CodeWriter writeField(String modifiers, String type, String name) {
        writeIndent().writeLine(modifiers + " " + type + " " + name + ";");
        return this;
    }

    public CodeWriter writeStatement(String statement) {
        writeIndent().writeLine(statement + ";");
        return this;
    }

    @Override
    public void close() {
        writer.close();
    }

    public void flush() {
        writer.flush();
    }
}